
package fr.afcepf.al22.orchestration.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "VerifCommandeImplService", targetNamespace = "http://impl.orchestration.al22.afcepf.fr/", wsdlLocation = "http://localhost:9090/WSOrchestrator/VerifCommandeImpl?wsdl")
@WebServiceClient(name = "VerifCommandeImplService", targetNamespace = "http://impl.orchestration.al22.afcepf.fr/", wsdlLocation = "file:/C:/Users/Stagiaire/Projet/ArtcoreParent/ArtcoreWeb/src/main/resources/wsdlOrchestrator.wsdl")
public class VerifCommandeImplService
    extends Service
{

    private final static URL VERIFCOMMANDEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VERIFCOMMANDEIMPLSERVICE_EXCEPTION;
    private final static QName VERIFCOMMANDEIMPLSERVICE_QNAME = new QName("http://impl.orchestration.al22.afcepf.fr/", "VerifCommandeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           // url = new URL("http://localhost:9090/WSOrchestrator/VerifCommandeImpl?wsdl");
            url = new URL("file:/C:/Users/Stagiaire/Projet/ArtcoreParent/ArtcoreWeb/src/main/resources/wsdlOrchestrator.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERIFCOMMANDEIMPLSERVICE_WSDL_LOCATION = url;
        VERIFCOMMANDEIMPLSERVICE_EXCEPTION = e;
    }

    public VerifCommandeImplService() {
        super(__getWsdlLocation(), VERIFCOMMANDEIMPLSERVICE_QNAME);
    }

    public VerifCommandeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERIFCOMMANDEIMPLSERVICE_QNAME, features);
    }

    public VerifCommandeImplService(URL wsdlLocation) {
        super(wsdlLocation, VERIFCOMMANDEIMPLSERVICE_QNAME);
    }

    public VerifCommandeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERIFCOMMANDEIMPLSERVICE_QNAME, features);
    }

    public VerifCommandeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerifCommandeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVerifCommande
     */
    @WebEndpoint(name = "VerifCommandeImplPort")
    public IVerifCommande getVerifCommandeImplPort() {
        return super.getPort(new QName("http://impl.orchestration.al22.afcepf.fr/", "VerifCommandeImplPort"), IVerifCommande.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVerifCommande
     */
    @WebEndpoint(name = "VerifCommandeImplPort")
    public IVerifCommande getVerifCommandeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.orchestration.al22.afcepf.fr/", "VerifCommandeImplPort"), IVerifCommande.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERIFCOMMANDEIMPLSERVICE_EXCEPTION!= null) {
            throw VERIFCOMMANDEIMPLSERVICE_EXCEPTION;
        }
        return VERIFCOMMANDEIMPLSERVICE_WSDL_LOCATION;
    }

}
