
package fr.afcepf.al22.wsartcore;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionStockImplService", targetNamespace = "http://wsartcore.al22.afcepf.fr/", wsdlLocation = "file:/C:/Users/Stagiaire/Projet/ArtcoreWebService/WSOrchestrator/src/main/resources/GestionStockImpl.wsdl")
public class GestionStockImplService
    extends Service
{

    private final static URL GESTIONSTOCKIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONSTOCKIMPLSERVICE_EXCEPTION;
    private final static QName GESTIONSTOCKIMPLSERVICE_QNAME = new QName("http://wsartcore.al22.afcepf.fr/", "GestionStockImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Stagiaire/Projet/ArtcoreWebService/WSOrchestrator/src/main/resources/GestionStockImpl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONSTOCKIMPLSERVICE_WSDL_LOCATION = url;
        GESTIONSTOCKIMPLSERVICE_EXCEPTION = e;
    }

    public GestionStockImplService() {
        super(__getWsdlLocation(), GESTIONSTOCKIMPLSERVICE_QNAME);
    }

    public GestionStockImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONSTOCKIMPLSERVICE_QNAME, features);
    }

    public GestionStockImplService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONSTOCKIMPLSERVICE_QNAME);
    }

    public GestionStockImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONSTOCKIMPLSERVICE_QNAME, features);
    }

    public GestionStockImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionStockImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGestionStock
     */
    @WebEndpoint(name = "GestionStockImplPort")
    public IGestionStock getGestionStockImplPort() {
        return super.getPort(new QName("http://wsartcore.al22.afcepf.fr/", "GestionStockImplPort"), IGestionStock.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGestionStock
     */
    @WebEndpoint(name = "GestionStockImplPort")
    public IGestionStock getGestionStockImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsartcore.al22.afcepf.fr/", "GestionStockImplPort"), IGestionStock.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONSTOCKIMPLSERVICE_EXCEPTION!= null) {
            throw GESTIONSTOCKIMPLSERVICE_EXCEPTION;
        }
        return GESTIONSTOCKIMPLSERVICE_WSDL_LOCATION;
    }

}
