
package fr.afcepf.al22.antivol;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AntivolCBImplService", targetNamespace = "http://antivol.al22.afcepf.fr/", wsdlLocation = "file:/C:/Users/Stagiaire/Projet/ArtcoreWebService/WSOrchestrator/src/main/resources/AntivolCBImpl.wsdl")
public class AntivolCBImplService
    extends Service
{

    private final static URL ANTIVOLCBIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANTIVOLCBIMPLSERVICE_EXCEPTION;
    private final static QName ANTIVOLCBIMPLSERVICE_QNAME = new QName("http://antivol.al22.afcepf.fr/", "AntivolCBImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Stagiaire/Projet/ArtcoreWebService/WSOrchestrator/src/main/resources/AntivolCBImpl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANTIVOLCBIMPLSERVICE_WSDL_LOCATION = url;
        ANTIVOLCBIMPLSERVICE_EXCEPTION = e;
    }

    public AntivolCBImplService() {
        super(__getWsdlLocation(), ANTIVOLCBIMPLSERVICE_QNAME);
    }

    public AntivolCBImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANTIVOLCBIMPLSERVICE_QNAME, features);
    }

    public AntivolCBImplService(URL wsdlLocation) {
        super(wsdlLocation, ANTIVOLCBIMPLSERVICE_QNAME);
    }

    public AntivolCBImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANTIVOLCBIMPLSERVICE_QNAME, features);
    }

    public AntivolCBImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AntivolCBImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAntivolCB
     */
    @WebEndpoint(name = "AntivolCBImplPort")
    public IAntivolCB getAntivolCBImplPort() {
        return super.getPort(new QName("http://antivol.al22.afcepf.fr/", "AntivolCBImplPort"), IAntivolCB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAntivolCB
     */
    @WebEndpoint(name = "AntivolCBImplPort")
    public IAntivolCB getAntivolCBImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://antivol.al22.afcepf.fr/", "AntivolCBImplPort"), IAntivolCB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANTIVOLCBIMPLSERVICE_EXCEPTION!= null) {
            throw ANTIVOLCBIMPLSERVICE_EXCEPTION;
        }
        return ANTIVOLCBIMPLSERVICE_WSDL_LOCATION;
    }

}
