
package fr.afcepf.al22.artcorewebservice.wspolice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVerifCasier", targetNamespace = "http://wspolice.artcorewebservice.al22.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVerifCasier {


    /**
     * 
     * @param prenom
     * @param birthday
     * @param nom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifCasier", targetNamespace = "http://wspolice.artcorewebservice.al22.afcepf.fr/", className = "fr.afcepf.al22.artcorewebservice.wspolice.VerifCasier")
    @ResponseWrapper(localName = "verifCasierResponse", targetNamespace = "http://wspolice.artcorewebservice.al22.afcepf.fr/", className = "fr.afcepf.al22.artcorewebservice.wspolice.VerifCasierResponse")
    public String verifCasier(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "birthday", targetNamespace = "")
        String birthday);

}
