
package fr.afcepf.al22.orchestration.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.al22.orchestration.interfaces.CheckResultProduitCommande;
import fr.afcepf.al22.orchestration.interfaces.ObjectFactory;
import fr.afcepf.al22.orchestration.interfaces.ProduitCommande;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVerifCommande", targetNamespace = "http://interfaces.orchestration.al22.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVerifCommande {


    /**
     * 
     * @param cbNumber
     * @param prenom
     * @param birthday
     * @param listeProduit
     * @param nom
     * @return
     *     returns fr.afcepf.al22.orchestration.interfaces.CheckResultProduitCommande
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifCommande", targetNamespace = "http://interfaces.orchestration.al22.afcepf.fr/", className = "fr.afcepf.al22.orchestration.interfaces.VerifCommande")
    @ResponseWrapper(localName = "verifCommandeResponse", targetNamespace = "http://interfaces.orchestration.al22.afcepf.fr/", className = "fr.afcepf.al22.orchestration.interfaces.VerifCommandeResponse")
    public CheckResultProduitCommande verifCommande(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "birthday", targetNamespace = "")
        String birthday,
        @WebParam(name = "cbNumber", targetNamespace = "")
        String cbNumber,
        @WebParam(name = "listeProduit", targetNamespace = "")
        List<ProduitCommande> listeProduit);

}
